"use client";


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar";
import StudentsProvider from "@/lib/context/collection/studentsContext";
import TutorsProvider from "@/lib/context/collection/tutorContext";
import InvoicesProvider from "@/lib/context/collection/invoiceContext";
import UserProvider from "@/lib/context/collection/userContext";
import StudentProvider from "@/lib/context/page/studentPageContext";
import AppProvider from "./appProviders";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <div className="flex">
            <Sidebar />
            <main className="flex-1 p-4">
              {children}
            </main>
          </div>
        </AppProvider>


      </body>
    </html>
  );
}
